/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controler.ProjetoController;
import controler.TarefaController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;

import model.Projeto;
import model.Tarefa;
import java.util.List;
import util.ColunaBotaoCellRenderer;
import util.ColunaPrazoCellRenderer;
import util.TarefaTableModel;

/**
 *
 * @author Alan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ProjetoController projetoController;
    TarefaController tarefaController;
    
    DefaultListModel projetosModel;
    TarefaTableModel tarefaModel;
    
    public TelaPrincipal() {
        initComponents();
       
        iniciarDadosController();
        iniciarComponentesModel();
        
        decorateTableTarefas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTarefas = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jPanelTitlo = new javax.swing.JPanel();
        jLabelTitlo = new javax.swing.JLabel();
        jLabelSubTitlo = new javax.swing.JLabel();
        jPanelProjetos = new javax.swing.JPanel();
        jLabelProjetos = new javax.swing.JLabel();
        jLabelProjetosAdd = new javax.swing.JLabel();
        jPanelTarefas = new javax.swing.JPanel();
        jLabelTarefas = new javax.swing.JLabel();
        jLabelTarefasAdd = new javax.swing.JLabel();
        jPanelProjetosList = new javax.swing.JPanel();
        jScrollPaneProjetos = new javax.swing.JScrollPane();
        jListProjetos = new javax.swing.JList<>();
        jPanelTarefasList = new javax.swing.JPanel();
        jPanelListaVazia = new javax.swing.JPanel();
        jLabelListaVaziaTitulo = new javax.swing.JLabel();
        jLabelListaVaziaSubTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTableTarefas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descriçao", "Prazo", "Tarefa Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTarefas.setGridColor(java.awt.Color.white);
        jTableTarefas.setRowHeight(50);
        jTableTarefas.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jTableTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTarefas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTarefas.setShowVerticalLines(false);
        jTableTarefas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTarefasMouseClicked(evt);
            }
        });
        jScrollPaneTarefas.setViewportView(jTableTarefas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Todo App");
        setMinimumSize(new java.awt.Dimension(600, 700));

        jPanelTitlo.setBackground(new java.awt.Color(0, 153, 102));

        jLabelTitlo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitlo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitlo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        jLabelTitlo.setText(" Todo App");

        jLabelSubTitlo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSubTitlo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubTitlo.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout jPanelTitloLayout = new javax.swing.GroupLayout(jPanelTitlo);
        jPanelTitlo.setLayout(jPanelTitloLayout);
        jPanelTitloLayout.setHorizontalGroup(
            jPanelTitloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTitloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSubTitlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTitloLayout.setVerticalGroup(
            jPanelTitloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitloLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitlo)
                .addGap(18, 18, 18)
                .addComponent(jLabelSubTitlo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProjetos.setBackground(java.awt.Color.white);
        jPanelProjetos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelProjetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelProjetos.setForeground(new java.awt.Color(0, 153, 102));
        jLabelProjetos.setText("Projetos");

        jLabelProjetosAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelProjetosAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProjetosAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelProjetosLayout = new javax.swing.GroupLayout(jPanelProjetos);
        jPanelProjetos.setLayout(jPanelProjetosLayout);
        jPanelProjetosLayout.setHorizontalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProjetosAdd)
                .addContainerGap())
        );
        jPanelProjetosLayout.setVerticalGroup(
            jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjetosAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelTarefas.setBackground(java.awt.Color.white);
        jPanelTarefas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTarefas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTarefas.setForeground(new java.awt.Color(0, 153, 102));
        jLabelTarefas.setText("Tarefas");

        jLabelTarefasAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jLabelTarefasAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTarefasAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(jLabelTarefasAdd)
                .addContainerGap())
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTarefasAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelProjetosList.setBackground(java.awt.Color.white);
        jPanelProjetosList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jListProjetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jListProjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListProjetos.setFixedCellHeight(50);
        jListProjetos.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jListProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProjetosMouseClicked(evt);
            }
        });
        jScrollPaneProjetos.setViewportView(jListProjetos);

        javax.swing.GroupLayout jPanelProjetosListLayout = new javax.swing.GroupLayout(jPanelProjetosList);
        jPanelProjetosList.setLayout(jPanelProjetosListLayout);
        jPanelProjetosListLayout.setHorizontalGroup(
            jPanelProjetosListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProjetosListLayout.setVerticalGroup(
            jPanelProjetosListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetosListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTarefasList.setBackground(java.awt.Color.white);
        jPanelTarefasList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTarefasList.setLayout(new java.awt.BorderLayout());

        jPanelListaVazia.setBackground(java.awt.Color.white);

        jLabelListaVaziaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelListaVaziaTitulo.setForeground(new java.awt.Color(0, 153, 102));
        jLabelListaVaziaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaTitulo.setText("Nenhuma tarefa por aqui :D");

        jLabelListaVaziaSubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelListaVaziaSubTitulo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelListaVaziaSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaVaziaSubTitulo.setText("Clique no botão \"+\" para adicionar um nova tarefa");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        javax.swing.GroupLayout jPanelListaVaziaLayout = new javax.swing.GroupLayout(jPanelListaVazia);
        jPanelListaVazia.setLayout(jPanelListaVaziaLayout);
        jPanelListaVaziaLayout.setHorizontalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGroup(jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListaVaziaSubTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelListaVaziaTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelListaVaziaLayout.setVerticalGroup(
            jPanelListaVaziaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaVaziaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelListaVaziaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelListaVaziaSubTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTarefasList.add(jPanelListaVazia, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitlo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProjetosList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTarefasList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTitlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProjetosList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTarefasList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelProjetosAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProjetosAddMouseClicked
        // TODO add your handling code here:
        TelaCadastroProjetos telaCadastroProjetos = new TelaCadastroProjetos(this, rootPaneCheckingEnabled);
        telaCadastroProjetos.setVisible(true);
        
        telaCadastroProjetos.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e){
                carregarProjetos();
            }
        });
        
    }//GEN-LAST:event_jLabelProjetosAddMouseClicked

    private void jLabelTarefasAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTarefasAddMouseClicked
        TelaCadastroTarefas telaCadastroTarefas = new TelaCadastroTarefas(this, rootPaneCheckingEnabled);
        int projetoIndex = jListProjetos.getSelectedIndex();
        Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
        telaCadastroTarefas.setProjeto(projeto);
        telaCadastroTarefas.setVisible(true); 
        
        telaCadastroTarefas.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e){
                carregarTarefas(projeto.getId());
            }
        });
    }//GEN-LAST:event_jLabelTarefasAddMouseClicked

    private void jTableTarefasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTarefasMouseClicked
        int rowIndex = jTableTarefas.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTarefas.columnAtPoint(evt.getPoint()); 
        Tarefa tarefa = tarefaModel.getTarefas().get(rowIndex);
        
        switch (columnIndex) {
            case 3:
                tarefaController.atualizar(tarefa);
                break;
            case 4:
                break;
            case 5:
                tarefaController.removerById(tarefa.getId());
                tarefaModel.getTarefas().remove(tarefa);
                
                int projetoIndex = jListProjetos.getSelectedIndex();
                Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
                carregarTarefas(projeto.getId());
                break;
        }
           
        
    }//GEN-LAST:event_jTableTarefasMouseClicked

    private void jListProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProjetosMouseClicked
        int projetoIndex = jListProjetos.getSelectedIndex();
        Projeto projeto = (Projeto) projetosModel.get(projetoIndex);
        carregarTarefas(projeto.getId());
    }//GEN-LAST:event_jListProjetosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelListaVaziaSubTitulo;
    private javax.swing.JLabel jLabelListaVaziaTitulo;
    private javax.swing.JLabel jLabelProjetos;
    private javax.swing.JLabel jLabelProjetosAdd;
    private javax.swing.JLabel jLabelSubTitlo;
    private javax.swing.JLabel jLabelTarefas;
    private javax.swing.JLabel jLabelTarefasAdd;
    private javax.swing.JLabel jLabelTitlo;
    private javax.swing.JList<String> jListProjetos;
    private javax.swing.JPanel jPanelListaVazia;
    private javax.swing.JPanel jPanelProjetos;
    private javax.swing.JPanel jPanelProjetosList;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPanel jPanelTarefasList;
    private javax.swing.JPanel jPanelTitlo;
    private javax.swing.JScrollPane jScrollPaneProjetos;
    private javax.swing.JScrollPane jScrollPaneTarefas;
    private javax.swing.JTable jTableTarefas;
    // End of variables declaration//GEN-END:variables
    
    public void decorateTableTarefas(){
        jTableTarefas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTableTarefas.getTableHeader().setBackground(new Color(0, 153, 102));
        jTableTarefas.getTableHeader().setForeground(new Color(255, 255, 255));
        
        jTableTarefas.getColumnModel().getColumn(2).setCellRenderer(new ColunaPrazoCellRenderer());
        
        jTableTarefas.getColumnModel().getColumn(4).setCellRenderer(new ColunaBotaoCellRenderer("edit"));
        jTableTarefas.getColumnModel().getColumn(5).setCellRenderer(new ColunaBotaoCellRenderer("delete"));
        //jTableTarefas.setAutoCreateRowSorter(true);
    }
    
    public void iniciarDadosController(){
        projetoController = new ProjetoController();
        tarefaController = new TarefaController();
    }
    
    public void iniciarComponentesModel(){
        projetosModel = new DefaultListModel();
        
        tarefaModel = new TarefaTableModel();
        jTableTarefas.setModel(tarefaModel);
        carregarProjetos();
    }
    
    public void carregarTarefas(int idProjeto){
        List<Tarefa> tarefas = tarefaController.listar(idProjeto);
        tarefaModel.setTarefas(tarefas);
        
        mostraJTableTarefas(!tarefas.isEmpty());
    }
    
    private void mostraJTableTarefas(boolean temTarefa){
        if(temTarefa){
            if (jPanelListaVazia.isVisible()) {
                jPanelListaVazia.setVisible(false);
                jPanelTarefasList.remove(jPanelListaVazia);
            }
            
            jPanelTarefasList.add(jScrollPaneTarefas);
            jScrollPaneTarefas.setVisible(true);
            jScrollPaneTarefas.setSize(jPanelTarefasList.getWidth(), 
                    jPanelTarefasList.getHeight());
        }else{
            if(jScrollPaneTarefas.isVisible()){
                jScrollPaneTarefas.setVisible(false);
                jPanelTarefasList.remove(jScrollPaneTarefas);
            }
            
            jPanelTarefasList.add(jPanelListaVazia);
            jPanelListaVazia.setVisible(true);
            jPanelListaVazia.setSize(jPanelTarefasList.getWidth(), 
                    jPanelTarefasList.getHeight());
        }   
    }
    
    public void carregarProjetos(){
        List<Projeto> projetos = projetoController.listar();
        projetosModel.clear();
        
        for (int i = 0; i < projetos.size(); i++) {
            projetosModel.addElement(projetos.get(i));
        }
        
        jListProjetos.setModel(projetosModel);
        
        if(!projetosModel.isEmpty()){
            jListProjetos.setSelectedIndex(0);
            Projeto projeto = (Projeto) projetosModel.get(0);
            carregarTarefas(projeto.getId());
        }
    }
}
