Algoritmo "Orientação a Objetos"

tipo
cadastroCliente = registro
    nome: caracter
    rg: caracter
    idade: inteiro
fimregistro

Var
cliente1: cadastroCliente

Inicio
escreval("Digite seu nome")
leia(cliente1.nome)

escreval("Digite seu rg")
leia(cliente1.rg)

escreval("Digite sua idade")
leia(cliente1.idade)

escreval("Nome: ", cliente1.nome)
escreval("RG: ", cliente1.rg)
escreval("Idade: ", cliente1.idade)


Fimalgoritmo